### ISSUE TITLE
Cant write zero float value

### ISSUE THREAD

**Issue by alicestoneprod** [hearhellacopters/bireader#1]
Hi, i cant write zero value as float by using writer.
![image](https://github.com/user-attachments/assets/65422763-62af-4352-84b7-a63d0446201b)
But successfully got reading zero value of float while im using bireader

**Comment by alicestoneprod** [comment]
![image](https://github.com/user-attachments/assets/73a1d16c-8121-44ec-93ef-7b6e0e2403f2)
fixed by this, but i think its not good if i need to write this code

**Comment by hearhellacopters** [comment]
Thank you for bringing this to my attention. I'll look into this now.

**Comment by hearhellacopters** [comment]
fixed in v1.0.58
