### ISSUE TITLE
Issue with writer.

### ISSUE THREAD

**Issue by alicestoneprod** [hearhellacopters/bireader#2]
When im writing (by biwriter) data to created buffer, script becomes slow and slow step by step.

**Comment by alicestoneprod** [comment]
`const getCsvData = (data) => {
  const writer = new biwriter(new Uint8Array(0))

  const splittedData = data.split("\r\n")
  const columnsTypes = splittedData[0].split(",")
  const columnsNames = splittedData[1].split(",").slice(1)
  const rowsData = splittedData.slice(2, splittedData.length - 1)

  for (let i = 0; i < 4; i++) {
    writer.writeByte(0)
  }

  writer.writeUInt16LE(columnsNames.length)
  writer.writeUInt32LE(rowsData.length)

  for (let i = 0; i < columnsNames.length; i++) {
    const nameLength = columnsNames[i].length
    const columnType = parseInt(columnsTypes[i + 1], 10)
    writer.writeUInt16LE(nameLength)
    writer.writeString(columnsNames[i], { length: nameLength })
    writer.writeByte(columnType)
  }

  console.log("Колонки вписаны")

  for (let i = 0; i < rowsData.length; i++) {
    const row = rowsData[i].split(",")

    for (let c = 0; c < row.length; c++) {
      const columnType = parseInt(columnsTypes[c], 10)
      const rowValue = row[c]

      switch (columnType) {
        case 1:
          const textLength = rowValue.length
          writer.writeUInt16LE(textLength)
          writer.writeString(rowValue)
          writer.offset -= 1
          break
        case 2:
          writer.writeUInt32LE(parseInt(rowValue, 10))
          break
        case 3:
          writer.writeInt32(parseInt(rowValue, 10))
          break
        case 4:
        case 5:
          if (rowValue === "0") {
            for (let q = 0; q < 4; q++) {
              writer.writeByte(0)
            }
          } else {
            writer.writeFloatLE(parseFloat(rowValue))
          }
          break
      }
    }
  }

  writer.writeByte(5)
  writer.writeString("THEND", { length: 5 })

  return writer.return()
}`

**Comment by alicestoneprod** [comment]
```
for (let i = 0; i < columnsNames.length; i++) {
const nameLength = columnsNames[i].length
const columnType = parseInt(columnsTypes[i + 1], 10)
writer.writeUInt16LE(nameLength)
writer.writeString(columnsNames[i], { length: nameLength })
writer.writeByte(columnType)
}
```

Its okay, but next for not okay, because script become slow with every new step.

**Comment by hearhellacopters** [comment]
In your code example you start the writer with a 0 length Uint8array. Every time you write a new value it has to create a new array and concat the two. I would try starting the biwriter with a larger buffer and using trim() before you end and see if that speed things up.

**Comment by alicestoneprod** [comment]
Will check it later.

**Comment by hearhellacopters** [comment]
I updated the readme with better example code and a note on how the biwriter works. I'm going to mark this issue as closed.
> **biwriter note:** while biwriter can be created with a 0 length Uint8array or Buffer, each new value write will create a new array and concat the two. For large data writes this will lead to a degraded performance. It's best to supply a larger than needed buffer to start and use .trim() after you're finished.
