### ISSUE TITLE
Cannot write float

### ISSUE THREAD

**Issue by alicestoneprod** [hearhellacopters/bireader#3]
Error: Value is out of range for the specified float length. min: -3.4028235e+38 max: 3.4028235e+38 value: 1.401298464324817e-45

**Comment by alicestoneprod** [comment]
![image](https://github.com/user-attachments/assets/7577b1b7-eafe-4256-936d-fcc2f4c77f0b)

**Comment by alicestoneprod** [comment]
Im writing converter, code large and need understanding. But i just cant write float =)

**Comment by alicestoneprod** [comment]
Seems 
![image](https://github.com/user-attachments/assets/e3cf1c14-640c-49b7-ac1c-6101b2561875)
it value from here. But really need fix

**Comment by alicestoneprod** [comment]
or maybe i should use other method?

**Comment by alicestoneprod** [comment]
im using this method
![image](https://github.com/user-attachments/assets/4e8534d8-7b8c-4ced-a65d-0f26e1a84bb5)

**Comment by alicestoneprod** [comment]
Here updated code (but maybe need check, so now it works fine)

```
const MIN_POSITIVE_FLOAT32 = Number.MIN_VALUE; // 1.401298464324817e-45
    const MAX_POSITIVE_FLOAT32 = 3.4028235e+38;
    const MIN_NEGATIVE_FLOAT32 = -3.4028235e+38;
    const MAX_NEGATIVE_FLOAT32 = -Number.MIN_VALUE; // -1.401298464324817e-45
    if( !((value === 0) || (value >= MIN_POSITIVE_FLOAT32 && value <= MAX_POSITIVE_FLOAT32) ||
        (value >= MIN_NEGATIVE_FLOAT32 && value <= MAX_NEGATIVE_FLOAT32)) ){
        _this.errorDump ? "[Error], hexdump:\n" + _this.hexdump() : "";
        throw new Error('Value is out of range for the specified float length.' +" min: " + MIN_NEGATIVE_FLOAT32 + " max: " + MAX_POSITIVE_FLOAT32 + " value: "+ value);
    }
```

**Comment by hearhellacopters** [comment]
Are you running this code on a browser? My node doesn't error in this way. But Number.MIN_VALUE is a safer way than hardcoded values so I'll update the code. I'll also add protections for double float (64 bit) as well.

**Comment by alicestoneprod** [comment]
im running code in node.js, i already maked converter with this half

Number.MIN_VALUE; // 1.401298464324817e-45
    const MAX_POSITIVE_FLOAT32 = 3.4028235e+38;
    const MIN_NEGATIVE_FLOAT32 = -3.4028235e+38;
    const MAX_NEGATIVE_FLOAT32 = -Number.MIN_VALUE; // -1.401298464324817e-45

**Comment by hearhellacopters** [comment]
Thanks, added to v1.0.59. marking as closed
