### ISSUE TITLE
Improve: Adding write bytes & read bytes method.

### ISSUE THREAD

**Issue by alicestoneprod** [hearhellacopters/bireader#4]
Please, add new 2 methods: 
Write bytes and read bytes, it can provide good code i guess, because now its not comfortable, i should add additional function, which using class and count of bytes, which i want to read

**Comment by alicestoneprod** [comment]
reader.readBytes(256) - returns array of numbers with length 256.

Im really not sure in write bytes, but read bytes seems will be good method!

**Comment by hearhellacopters** [comment]
You can easily make an array of bytes with this one line of code.
```javascript
const numbers = Array.from({length: 256}, () => br.ubyte());
```
You can also get a sub Buffer using `br.extract(256,true)`, which you could use as number array.

Writing you would need an array. But it's also possible with just one line of code.
```javascript
const numbers = [...Array(256).keys()];
for(const value in numbers) bw.ubyte(value);
```
If this was a more involved feature I would think about adding it but it seem situational and very easy to do in a single line of code.

**Comment by hearhellacopters** [comment]
I added these in version 2.0.

Do note that ``bireader`` and ``biwriter`` classes will be deprecated in 3.0.

The new classes are ``BiReader`` and ``BiWriter`` with easier aliases as get / set now.

**Comment by alicestoneprod** [comment]
Thanks for your attention.
You`re finally created these methods. :)
